#
#  ISC License
#
#  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
"""Generate the ICD's two generated parts (ECSS-E-ST-40C E.2.1<5.3>;
remediation R14):

* ``compliance/docs/ICD_scenario_fields.md``: every field of the scenario
  JSON (the schema dataclasses in ``spacemissionstudio/schema``) with its
  type, default and the comment on its source line (unit, range, meaning),
  for interface SRS-I-01;
* ``compliance/docs/ICD_cli.md``: every command of the command-line
  interface with its arguments and help text, from the CLI's own argparse
  parser, for interface SRS-I-02.

The code is the definition; these files are generated views of it. Usage::

    python compliance/tools/build_icd_schema.py
"""

from __future__ import annotations

import argparse
import dataclasses
import inspect
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT.parent))

from spacemissionstudio import cli  # noqa: E402
from spacemissionstudio.schema import command, scenario  # noqa: E402


def _default(f: dataclasses.Field) -> str:
    if f.default is not dataclasses.MISSING:
        return repr(f.default)
    if f.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
        return repr(f.default_factory())  # type: ignore[misc]
    return "required"


def _comments(cls) -> dict:
    """``{field: trailing comment}`` from the class source."""
    comments = {}
    for line in inspect.getsource(cls).splitlines():
        match = re.match(r"^\s+([a-z_][a-z0-9_]*)\s*:\s*[^=#]+(?:=[^#]*)?#\s*(.+)$", line)
        if match:
            comments[match.group(1)] = match.group(2).strip()
    return comments


def _cell(text) -> str:
    return " ".join(str(text or "").split()).replace("|", "/")


def build_cli() -> int:
    """Write ``ICD_cli.md`` from :func:`spacemissionstudio.cli.build_parser`."""
    parser = cli.build_parser()
    subparsers = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    helps = {choice.dest: choice.help for choice in subparsers._choices_actions}
    lines = ["# Command-line interface (generated)", "",
             "Generated by `compliance/tools/build_icd_schema.py` from the CLI's argparse parser "
             "(`spacemissionstudio/cli.py`, `build_parser`), which is the definition of interface SRS-I-02. "
             "Usage: `spacemissionstudio <command> [arguments]`. Exit codes are in the ICD (ICD-02).", ""]
    for name, sub in subparsers.choices.items():
        lines += [f"## `{name}`", "", _cell(helps.get(name)), "", "| Argument | Help |", "|---|---|"]
        for action in sub._actions:
            if isinstance(action, argparse._HelpAction):
                continue
            argument = ", ".join(action.option_strings) or action.dest
            if action.choices:
                argument += " {" + ",".join(map(str, action.choices)) + "}"
            lines.append(f"| `{argument}` | {_cell(action.help)} |")
        lines.append("")
    out = ROOT / "docs" / "ICD_cli.md"
    out.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8")  # one final newline (pre-commit end-of-file-fixer)
    print(f"{out.name}: {len(subparsers.choices)} commands")
    return 0


def build() -> int:
    classes = [c for module in (scenario, command) for _n, c in inspect.getmembers(module, inspect.isclass)
               if dataclasses.is_dataclass(c) and c.__module__ == module.__name__]
    lines = ["# Scenario file fields (generated)", "",
             "Generated by `compliance/tools/build_icd_schema.py` from the schema dataclasses "
             "(`spacemissionstudio/schema/scenario.py`, `command.py`), which are the definition of the "
             "scenario JSON (ICD interface SRS-I-01). Units and ranges are those written on each field's "
             "source line; the full validation rules are each class's `validate()`.", ""]
    for cls in sorted(classes, key=lambda c: (c.__name__ != "Scenario", c.__name__)):
        doc = (inspect.getdoc(cls) or "").split("\n\n")[0].replace("\n", " ")
        if doc.startswith(f"{cls.__name__}("):  # the dataclass's generated signature, not a docstring
            doc = "Top-level scenario object (the JSON file's root)." if cls is scenario.Scenario else ""
        lines += [f"## {cls.__name__}", "", doc, "", "| Field | Type | Default | Unit / note |", "|---|---|---|---|"]
        notes = _comments(cls)
        for f in dataclasses.fields(cls):
            if f.name.startswith("_"):
                continue
            kind = getattr(f.type, "__name__", str(f.type)).replace("typing.", "").replace("|", "/")
            note = notes.get(f.name, "").replace("|", "/")
            lines.append(f"| `{f.name}` | {kind} | `{_default(f)[:60]}` | {note[:160]} |")
        lines.append("")
    out = ROOT / "docs" / "ICD_scenario_fields.md"
    out.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8")  # one final newline (pre-commit end-of-file-fixer)
    print(f"{out.name}: {len(classes)} classes")
    return build_cli()


if __name__ == "__main__":
    sys.exit(build())
