#
#  ISC License
#
#  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
"""Generate ``compliance/docs/ICD_scenario_fields.md``: every field of the
scenario JSON (the schema dataclasses in ``spacemissionstudio/schema``) with
its type, default and the comment on its source line (unit, range, meaning),
for the ICD's interface SRS-I-01 (ECSS-E-ST-40C E.2.1<5.3>d; remediation
R14). The dataclasses are the definition; this file is a generated view of
them. Usage::

    python compliance/tools/build_icd_schema.py
"""

from __future__ import annotations

import dataclasses
import inspect
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT.parent))

from spacemissionstudio.schema import command, scenario  # noqa: E402


def _default(f: dataclasses.Field) -> str:
    if f.default is not dataclasses.MISSING:
        return repr(f.default)
    if f.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
        return repr(f.default_factory())  # type: ignore[misc]
    return "required"


def _comments(cls) -> dict:
    """``{field: trailing comment}`` from the class source."""
    comments = {}
    for line in inspect.getsource(cls).splitlines():
        match = re.match(r"^\s+([a-z_][a-z0-9_]*)\s*:\s*[^=#]+(?:=[^#]*)?#\s*(.+)$", line)
        if match:
            comments[match.group(1)] = match.group(2).strip()
    return comments


def build() -> int:
    classes = [c for module in (scenario, command) for _n, c in inspect.getmembers(module, inspect.isclass)
               if dataclasses.is_dataclass(c) and c.__module__ == module.__name__]
    lines = ["# Scenario file fields (generated)", "",
             "Generated by `compliance/tools/build_icd_schema.py` from the schema dataclasses "
             "(`spacemissionstudio/schema/scenario.py`, `command.py`), which are the definition of the "
             "scenario JSON (ICD interface SRS-I-01). Units and ranges are those written on each field's "
             "source line; the full validation rules are each class's `validate()`.", ""]
    for cls in sorted(classes, key=lambda c: (c.__name__ != "Scenario", c.__name__)):
        doc = (inspect.getdoc(cls) or "").split("\n\n")[0].replace("\n", " ")
        if doc.startswith(f"{cls.__name__}("):  # the dataclass's generated signature, not a docstring
            doc = "Top-level scenario object (the JSON file's root)." if cls is scenario.Scenario else ""
        lines += [f"## {cls.__name__}", "", doc, "", "| Field | Type | Default | Unit / note |", "|---|---|---|---|"]
        notes = _comments(cls)
        for f in dataclasses.fields(cls):
            if f.name.startswith("_"):
                continue
            kind = getattr(f.type, "__name__", str(f.type)).replace("typing.", "").replace("|", "/")
            note = notes.get(f.name, "").replace("|", "/")
            lines.append(f"| `{f.name}` | {kind} | `{_default(f)[:60]}` | {note[:160]} |")
        lines.append("")
    out = ROOT / "docs" / "ICD_scenario_fields.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{out.name}: {len(classes)} classes")
    return 0


if __name__ == "__main__":
    sys.exit(build())
