#
#  ISC License
#
#  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
"""Measure run time and peak memory on the reference PC (SRS-P-09,
SRS-R-02; human action H13, decision 19).

Two cases, both run through the command line (``spacemissionstudio run``)
in a child process, so the figures cover the whole tool (scenario load,
Basilisk build, the run and the CSV export):

* ``day``: SRS-P-09, a one-day LEO run with drag and a degree-20 field.
  Requirement: under 5 minutes.
* ``year``: SRS-R-02, a one-year run recorded every 60 s. Requirement:
  memory below 2 GB.

Both use a 550 km Sun-synchronous orbit, a degree-20 Earth field,
NRLMSISE-00 drag with the bundled real space weather (CelesTrak observed
values and NASA MSFC predictions), the default 10 s dynamics step and a
500 kg spacecraft. The orbit is high enough to survive a year of drag.

Peak memory is the child's maximum resident set size (``os.wait4``);
it is not available on Windows, where it is reported as not measured.

Usage::

    python compliance/tools/measure_performance.py [--case day|year|all] [--write]

``--write`` stores the results in ``compliance/performance.md``.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import subprocess
import sys
import tempfile
import time
from datetime import date
from pathlib import Path

from spacemissionstudio.engine.orbit_design import sun_synchronous_inclination_deg

ROOT = Path(__file__).resolve().parent.parent
TOOL = ROOT.parent
TEMPLATE = TOOL / "spacemissionstudio" / "scenarios" / "templates" / "02_elliptical_orbit_with_perturbations.json"

EARTH_RADIUS_KM = 6378.1363  # [km] equatorial radius, as the tool's environment constants
ALTITUDE_KM = 550.0  # [km]
GRAVITY_DEGREE = 20  # [-] spherical-harmonic degree and order
EPOCH_UTC = "2026-01-01T00:00:00"

# case: (requirement, duration [days], record interval [s], limit, unit of the limit)
CASES = {
    "day": ("SRS-P-09", 1.0, 0.0, 300.0, "s"),  # 1 day, every step recorded; limit 5 min [s]
    "year": ("SRS-R-02", 365.0, 60.0, 2048.0, "MiB"),  # 365 days at 60 s; limit 2 GB [MiB]
}


def scenario_for(duration_days: float, record_interval_s: float) -> dict:
    """Build the measurement scenario from template 02, so it follows the
    current schema.

    :param duration_days: simulated time [days].
    :param record_interval_s: recording interval [s]; 0 records every step.
    :return: the scenario as a JSON-compatible dict.
    """
    scenario = json.loads(TEMPLATE.read_text(encoding="utf-8"))
    scenario["name"] = f"Reference PC measurement, {duration_days:g} days"
    scenario["description"] = "Generated by compliance/tools/measure_performance.py (H13)."
    scenario["epoch_utc"] = EPOCH_UTC
    scenario["gravity"]["central_body_degree"] = GRAVITY_DEGREE
    scenario["sim_settings"].update(duration_days=duration_days, dynamics_task_rate_s=10.0,
                                    record_interval_s=record_interval_s)
    spacecraft = scenario["spacecraft"][0]
    spacecraft["orbit"].update(semi_major_axis_km=EARTH_RADIUS_KM + ALTITUDE_KM, eccentricity=0.0,
                               inclination_deg=round(sun_synchronous_inclination_deg(EARTH_RADIUS_KM + ALTITUDE_KM), 2), arg_periapsis_deg=0.0)
    spacecraft["enable_drag"] = True
    spacecraft["drag_coeff"] = 2.2  # [-]
    spacecraft["drag_area_m2"] = 1.0  # [m^2]
    return scenario


def _peak_rss_mib(rusage) -> float:
    """``ru_maxrss`` in MiB: kibibytes on Linux, bytes on macOS."""
    divisor = 1024.0 * 1024.0 if sys.platform == "darwin" else 1024.0
    return rusage.ru_maxrss / divisor


def measure(case: str) -> dict:
    """Run one case in a child process and measure it.

    :param case: a key of :data:`CASES`.
    :return: wall time [s], peak memory [MiB] (None on Windows), the exit
        code and whether the requirement is met.
    """
    requirement, duration_days, record_interval_s, limit, unit = CASES[case]
    with tempfile.TemporaryDirectory() as work:
        path = Path(work) / f"{case}.json"
        path.write_text(json.dumps(scenario_for(duration_days, record_interval_s)), encoding="utf-8")
        command = [sys.executable, "-m", "spacemissionstudio.cli", "run", str(path), "--out-dir", str(Path(work) / "out")]
        start = time.perf_counter()
        child = subprocess.Popen(command, cwd=TOOL, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)  # noqa: S603
        peak_mib = None
        if hasattr(os, "wait4"):
            _pid, status, rusage = os.wait4(child.pid, 0)
            returncode = os.waitstatus_to_exitcode(status)
            peak_mib = _peak_rss_mib(rusage)
            stderr = child.stderr.read().decode(errors="replace")
        else:
            stderr = child.communicate()[1].decode(errors="replace")
            returncode = child.returncode
        wall_s = time.perf_counter() - start
    value = wall_s if unit == "s" else peak_mib
    return {"case": case, "requirement": requirement, "duration_days": duration_days,
            "record_interval_s": record_interval_s, "wall_s": round(wall_s, 1),
            "peak_mib": None if peak_mib is None else round(peak_mib, 1), "exit_code": returncode,
            "limit": f"{limit:g} {unit}",
            "met": returncode == 0 and value is not None and value < limit,
            "stderr_tail": stderr.strip().splitlines()[-3:]}


def machine() -> dict:
    """The reference PC as this script sees it."""
    try:
        import importlib.metadata as metadata
        basilisk = metadata.version("bsk")
    except Exception:  # noqa: BLE001 -- report, do not fail, when the version is unknown
        basilisk = "unknown"
    memory_gib = None
    if hasattr(os, "sysconf") and "SC_PHYS_PAGES" in os.sysconf_names:
        memory_gib = round(os.sysconf("SC_PHYS_PAGES") * os.sysconf("SC_PAGE_SIZE") / 1024 ** 3, 1)
    return {"os": platform.platform(), "machine": platform.machine(), "cpus": os.cpu_count(),
            "memory_gib": memory_gib, "python": platform.python_version(), "basilisk": basilisk}


def report(host: dict, results: list) -> str:
    """The results as Markdown."""
    lines = [f"# Reference PC measurements ({date.today().isoformat()})", "",
             "Generated by `compliance/tools/measure_performance.py` (SRS-P-09, SRS-R-02; H13, decision 19).", "",
             "| Item | Value |", "|---|---|"]
    lines += [f"| {key} | {value} |" for key, value in host.items()]
    lines += ["", "| Requirement | Case | Wall time [s] | Peak memory [MiB] | Limit | Exit code | Met |",
              "|---|---|---|---|---|---|---|"]
    for r in results:
        peak = "not measured" if r["peak_mib"] is None else r["peak_mib"]
        lines.append(f"| {r['requirement']} | {r['duration_days']:g} d, record {r['record_interval_s']:g} s "
                     f"| {r['wall_s']} | {peak} | {r['limit']} | {r['exit_code']} | {'yes' if r['met'] else 'no'} |")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--case", choices=(*CASES, "all"), default="all")
    parser.add_argument("--write", action="store_true", help="store the results in compliance/performance.md")
    args = parser.parse_args(argv)
    host = machine()
    results = [measure(case) for case in (CASES if args.case == "all" else [args.case])]
    text = report(host, results)
    print(text)
    print(json.dumps(results, indent=1))
    if args.write:
        (ROOT / "performance.md").write_text(text, encoding="utf-8")
    return 0 if all(r["met"] for r in results) else 1


if __name__ == "__main__":
    sys.exit(main())
