#
#  ISC License
#
#  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

"""Copies the Basilisk sources the flight-software export needs, unchanged,
from the revision the pinned Basilisk wheel was built from.

Usage (from SpaceMissionStudio/, in a Basilisk git clone that has the
``v2.12.0`` tag's objects)::

    python scripts/vendor_basilisk_fsw.py [--repo ..]

For each module in ``spacemissionstudio.fsw_export.catalog.MODULES`` it
follows ``#include "..."`` lines through the module's header and source,
the message payload headers behind each ``cMsgCInterface/<Type>Msg_C.h``
(generated by Basilisk's build, so not in the tree), and the ``.c`` file
next to each included utility header. The files are written byte for
byte with ``git show <revision>:src/<path>`` into one zip,
``spacemissionstudio/fsw_export/basilisk_fsw_sources.zip``, and
``basilisk_fsw_sources.json`` records each file's git blob hash so
``tests/test_fsw_vendored_sources.py`` can check that none was changed.

A zip rather than loose files: several of these Basilisk files end lines
with spaces, and the repository's whitespace hooks would rewrite loose
copies. The zip's entries carry a fixed date, so the same revision always
gives the same zip.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from spacemissionstudio.fsw_export.catalog import (  # noqa: E402
    BASILISK_REVISION,
    BASILISK_VERSION,
    EXTRA_FILES,
    LICENSE_FILE,
    MODULES,
)

PACKAGE_DIR = HERE.parent / "spacemissionstudio" / "fsw_export"
ARCHIVE = PACKAGE_DIR / "basilisk_fsw_sources.zip"
MANIFEST = PACKAGE_DIR / "basilisk_fsw_sources.json"
_ZIP_DATE = (2026, 1, 1, 0, 0, 0)
_INCLUDE = re.compile(r'^\s*#\s*include\s+"([^"]+)"', re.M)
_C_MSG = re.compile(r"cMsgCInterface/(\w+)Msg_C\.h$")
# Standard C headers some Basilisk files include with quotes ("math.h").
_STANDARD_HEADERS = {"math.h", "string.h", "stdio.h", "stdlib.h", "stdint.h", "stddef.h", "float.h", "limits.h"}


def _git(repo: Path, *args: str) -> bytes:
    return subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True).stdout  # noqa: S603,S607


def _tree(repo: Path) -> dict:
    """``{path under src/: blob hash}`` at the revision."""
    listing = _git(repo, "ls-tree", "-r", BASILISK_REVISION, "src").decode()
    blobs = {}
    for line in listing.splitlines():
        meta, path = line.split("\t", 1)
        blobs[path[len("src/"):]] = meta.split()[2]
    return blobs


def closure(repo: Path, blobs: dict):
    """The files the modules need, and the message types they use."""
    wanted = set()
    message_types = set()
    todo = [path for module in MODULES.values() for path in (module.header, module.source)] + list(EXTRA_FILES)
    while todo:
        path = todo.pop()
        if path in wanted:
            continue
        if path not in blobs:
            raise SystemExit(f"{path} is not in Basilisk {BASILISK_REVISION}")
        wanted.add(path)
        if path.endswith(".in"):
            continue
        text = _git(repo, "show", f"{BASILISK_REVISION}:src/{path}").decode("utf-8", "replace")
        for include in _INCLUDE.findall(text):
            generated = _C_MSG.search(include)
            if generated:
                message_types.add(generated.group(1))
                todo.append(f"architecture/msgPayloadDefC/{generated.group(1)}MsgPayload.h")
                continue
            for candidate in (include, f"{path.rsplit('/', 1)[0]}/{include}"):
                if candidate in blobs:
                    todo.append(candidate)
                    companion = candidate.rsplit(".", 1)[0] + ".c"
                    if candidate.endswith(".h") and companion in blobs:
                        todo.append(companion)
                    break
            else:
                if include in _STANDARD_HEADERS:
                    continue
                raise SystemExit(f"{path}: cannot resolve #include \"{include}\"")
    return sorted(wanted), sorted(message_types)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", type=Path, default=HERE.parent.parent, help="the Basilisk git clone")
    args = parser.parse_args(argv)
    blobs = _tree(args.repo)
    files, message_types = closure(args.repo, blobs)
    manifest = {"basilisk_version": BASILISK_VERSION, "basilisk_revision": BASILISK_REVISION,
                "licence": LICENSE_FILE, "message_types": message_types, "files": {}}
    with zipfile.ZipFile(ARCHIVE, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in files + [LICENSE_FILE]:
            git_path = LICENSE_FILE if path == LICENSE_FILE else f"src/{path}"
            entry = zipfile.ZipInfo(path, _ZIP_DATE)
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.external_attr = 0o644 << 16
            archive.writestr(entry, _git(args.repo, "show", f"{BASILISK_REVISION}:{git_path}"))
            manifest["files"][path] = (_git(args.repo, "rev-parse", f"{BASILISK_REVISION}:{LICENSE_FILE}").decode().strip()
                                       if path == LICENSE_FILE else blobs[path])
    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    print(f"{len(files)} files, {len(message_types)} message types, from Basilisk {BASILISK_VERSION} "
          f"({BASILISK_REVISION[:9]}) into {ARCHIVE.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
