#
#  ISC License
#
#  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

"""The documents written into an export: ``ICD.md`` (the interfaces),
``TRACEABILITY.md`` (GUI parameter -> scenario -> config symbol -> source
file) and ``README.md`` (building, running, provenance).

The ICD uses the terms of ECSS-E-ST-40C (software item, external
interface, interface control document; its Annex E lists what an ICD
covers) where they fit. It describes this export; it does not claim that
the export or the document conforms to the standard.
"""

from __future__ import annotations

from typing import Dict, List

from . import cdecl, sources
from .catalog import MODULES
from .model import FswCapture, Port


def _payload_fields(message_type: str) -> List[cdecl.Field]:
    path = f"architecture/msgPayloadDefC/{message_type}MsgPayload.h"
    try:
        return cdecl.parse_struct(sources.read_text(path), f"{message_type}MsgPayload")
    except (sources.VendoredSourceError, cdecl.StructNotFound):
        return []


def _escape(text: str) -> str:
    return text.replace("|", "\\|")


def _rate_text(rate_ns: int) -> str:
    return f"{rate_ns * 1e-9:g} s ({1e9 / rate_ns:g} Hz)"


def _port_section(cap: FswCapture, port: Port, heading: str, producer_label: str, consumer_label: str) -> List[str]:
    mtype = cap.message_types[port.message_type]
    lines = [f"#### {heading} `{port.name}`", "",
             "| Item | Value |", "|---|---|",
             f"| Message type | `{port.message_type}MsgPayload` |",
             f"| Size | {mtype.size} bytes |", f"| Layout hash | `{mtype.hash}` |",
             f"| {producer_label} | `{_escape(port.producer)}` |",
             f"| {consumer_label} | {', '.join(f'`{c}`' for c in port.consumers) or '-'} |",
             f"| Rate | every step, {_rate_text(cap.rate_ns)} |", ""]
    shapes = {f["name"]: f["shape"] for f in mtype.layout["fields"]}
    declared = _payload_fields(port.message_type)
    if declared:
        lines += ["| Field | C type | Elements | Unit | Description |", "|---|---|---|---|---|"]
        for f in declared:
            shape = "x".join(str(n) for n in shapes.get(f.name, [])) or "1"
            lines.append(f"| `{f.name}` | `{f.c_type}` | {shape} | {_escape(f.unit) or '-'} | "
                         f"{_escape(f.description) or '-'} |")
        lines.append("")
    return lines


def _flow_diagram(cap: FswCapture) -> List[str]:
    lines = ["```mermaid", "flowchart LR"]
    for p in cap.inputs:
        lines.append(f'    in_{p.name}(["{p.name}"])')
    for m in cap.modules:
        lines.append(f'    {m.name}["{m.name}<br/>{m.python_name}"]')
    for p in cap.outputs:
        lines.append(f'    out_{p.name}(["{p.name}"])')
    for c in cap.constants:
        lines.append(f'    cfg_{c.name}[("{c.name}")]')
    for m in cap.modules:
        for link in m.inputs:
            if link.kind == "module":
                lines.append(f"    {link.ref.split('.')[0]} --> {m.name}")
            elif link.kind == "input":
                lines.append(f"    in_{link.ref} --> {m.name}")
            elif link.kind == "constant":
                lines.append(f"    cfg_{link.ref} -.-> {m.name}")
    for p in cap.outputs:
        lines.append(f"    {p.producer.split('.')[0]} --> out_{p.name}")
    lines += ["```", ""]
    return lines


def icd_markdown(cap: FswCapture) -> str:
    lines = [f"# Interface Control Document: flight software of {cap.spacecraft}", "",
             f"Generated by SpaceMissionStudio {cap.exported_with.get('spacemissionstudio', '')} from the scenario "
             f"\"{cap.scenario_name}\". It describes the interfaces of this export as recorded from the simulation; "
             "regenerate it with the export rather than editing it.", "",
             "## 1 Purpose", "",
             f"This document describes the external interfaces of one software item, the attitude flight software "
             f"of {cap.spacecraft}: the messages it reads, the commands it writes, its telemetry and its fixed "
             "configuration. The headings follow the content ECSS-E-ST-40C (Annex E) lists for an interface control "
             "document. This export does not claim conformance to that standard.", "",
             "## 2 Reference documents", "",
             f"- Basilisk {cap.basilisk_version}, revision `{cap.basilisk_revision}`: the module sources in "
             "`basilisk/`, unchanged (ISC licence, `basilisk/LICENSE`).",
             f"- SpaceMissionStudio scenario \"{cap.scenario_name}\", configuration digest `{cap.config_digest}`.",
             "- `TRACEABILITY.md`: where each parameter comes from.",
             "- `README.md`: building and running this package.", "",
             "## 3 Terms", "",
             "- **Port**: a message crossing the software item's boundary. Inputs come from the simulation, outputs "
             "go to the actuators, telemetry is every other module output.",
             "- **Configuration message (constant)**: a message written once at start-up and never again.",
             "- **Rate group**: modules run together at one rate, in a fixed order.",
             "- **Layout hash**: 16 hex digits identifying a payload type and its exact binary layout.", "",
             "## 4 Software overview", "",
             f"One rate group at {_rate_text(cap.rate_ns)}, in this order (the order Basilisk ran them):", "",
             "| Order | Module | Basilisk module | Source |", "|---|---|---|---|"]
    for i, m in enumerate(cap.modules, 1):
        lines.append(f"| {i} | `{m.name}` | `{m.python_name}` | `basilisk/{MODULES[m.python_name].source}` |")
    lines.append("")
    if cap.priming_resets:
        lines += [f"After the step at {cap.priming_time_ns * 1e-9:g} s, "
                  f"{', '.join(f'`{n}`' for n in cap.priming_resets)} is reset once more, as SpaceMissionStudio "
                  "does in the simulation so that momentum management starts from real wheel speeds.", ""]
    lines += _flow_diagram(cap)
    lines += ["## 5 Interfaces", "", "### 5.1 Inputs", ""]
    for p in cap.inputs:
        lines += _port_section(cap, p, "Input", "Produced by (simulation)", "Read by")
    lines += ["### 5.2 Outputs (actuator commands)", ""]
    for p in cap.outputs:
        lines += _port_section(cap, p, "Output", "Written by", "Read by (simulation)")
    lines += ["### 5.3 Telemetry", "", "Every other module output, for monitoring and comparison:", "",
              "| Port | Message type | Size | Layout hash | Written by |", "|---|---|---|---|---|"]
    for p in cap.telemetry:
        mtype = cap.message_types[p.message_type]
        lines.append(f"| `{p.name}` | `{p.message_type}MsgPayload` | {mtype.size} | `{mtype.hash}` | `{p.producer}` |")
    lines += ["", "### 5.4 Configuration messages", "",
              "| Name | Message type | Read by | Source |", "|---|---|---|---|"]
    for c in cap.constants:
        source = f"`{c.scenario_path}`" if c.scenario_path else "-"
        lines.append(f"| `{c.name}` | `{c.message_type}MsgPayload` | {', '.join(f'`{x}`' for x in c.consumers)} | "
                     f"{source} |")
    lines += ["", "Their values are in `generated/fsw_config.c` (`fsw_constant_<name>`).", "",
              "### 5.5 Not in this export", ""]
    if cap.not_exported:
        lines += ["The simulation also runs this flight software, written in Python, which is not exported:", ""]
        lines += [f"- {item}" for item in cap.not_exported]
    else:
        lines.append("Nothing: the simulation runs no other flight software for this spacecraft.")
    lines += ["", "## 6 Validation approach", "",
              f"- `tests/test_<module>.c`: each module alone, fed what it read at time 0 of a {len(cap.times_ns)}-step "
              "recorded run; its outputs must equal what it wrote.",
              f"- `replay` (CTest): the whole software item fed the recorded inputs of all {len(cap.times_ns)} steps; "
              "every output and telemetry port must equal the simulation's, to a relative 1e-9 and an absolute "
              "1e-12.",
              "- `generated/fsw_layout_check.c`: the build stops if any payload's size or field offsets differ from "
              "the simulation's.",
              "- Software in the loop (`fsw_host sil`, `SIL_CONTRACT.md`): SpaceMissionStudio flies the spacecraft "
              "with this software, step by step, and compares every output and telemetry port with its own modules; "
              "before the first step it checks each port's name, size and layout hash.", "",
              "Not covered: timing on target hardware, real sensors (the inputs are the simulation's navigation "
              "messages), and modes or settings the scenario does not use.", "",
              "## 7 Assumptions and limits", "",
              "- Navigation inputs are what the simulation's `simpleNav` gives: the true state, or with the "
              "spacecraft's navigation error a bounded random walk on it (User Manual, \"Navigation error\").",
              "- Payloads are exchanged in the host's byte order; the traces in `tests/data/` are little-endian.",
              "- The scheduler runs one rate group; it is the rate the simulation ran the modules at.", ""]
    return "\n".join(lines)


def traceability_markdown(cap: FswCapture, config_lines: Dict[str, int]) -> str:
    lines = [f"# Traceability: flight software of {cap.spacecraft}", "",
             "Where each exported value comes from: the GUI control, the scenario field, the symbol in "
             "`generated/fsw_config.c` that holds it (with its line), and the Basilisk source that uses it. "
             f"Scenario paths are under `spacecraft[{cap.spacecraft}]`. A field with no GUI or scenario source keeps "
             "the module's starting value (Basilisk's wrapper zeroes the configuration) or the value "
             "SpaceMissionStudio fixes, as the note says.", "",
             "## Module parameters", "",
             "| GUI | Scenario | Config symbol | fsw_config.c line | Value | Source file |",
             "|---|---|---|---|---|---|"]
    for m in cap.modules:
        source = f"`basilisk/{MODULES[m.python_name].source}`"
        for p in m.params:
            value = p.value if not isinstance(p.value, dict) else f"{p.value.get('message_type')} struct"
            text = str(value)
            if len(text) > 40:
                text = text[:37] + "..."
            scenario = f"`{p.scenario_path}`" if p.scenario_path else (_escape(p.note) or "module default")
            lines.append(f"| {_escape(p.gui)} | {scenario} | `fsw_modules.{m.name}.{p.name}` | "
                         f"{config_lines.get(f'{m.name}.{p.name}', '-')} | `{_escape(text)}` | {source} |")
    lines += ["", "## Configuration messages", "",
              "| GUI | Scenario | Config symbol | fsw_config.c line | Note |", "|---|---|---|---|---|"]
    for c in cap.constants:
        scenario = f"`{c.scenario_path}`" if c.scenario_path else "-"
        lines.append(f"| {_escape(c.gui)} | {scenario} | `fsw_constant_{c.name}` | "
                     f"{config_lines.get(f'constant.{c.name}', '-')} | {_escape(c.note) or '-'} |")
    lines.append("")
    return "\n".join(lines)


def readme_markdown(cap: FswCapture) -> str:
    return "\n".join([
        f"# Flight software of {cap.spacecraft}", "",
        f"Exported by SpaceMissionStudio {cap.exported_with.get('spacemissionstudio', '')} from the scenario "
        f"\"{cap.scenario_name}\": the attitude flight software the simulation runs, as a standalone C99 project. "
        "It needs CMake and a C compiler only: no Python, no Basilisk installation.", "",
        "## Build and test", "", "```sh", "cmake -S . -B build", "cmake --build build", "ctest --test-dir build",
        "./build/fsw_host info", "```", "",
        "With Visual Studio (Windows, best effort): `cmake --build build --config Release` and "
        "`ctest --test-dir build -C Release`.", "",
        "`ctest` runs one unit test per module and `replay`, which feeds the whole software the inputs recorded "
        f"from {len(cap.times_ns)} simulation steps and compares every output with the simulation's.", "",
        "## Using it", "", "```c", '#include "fsw_scheduler.h"', '#include "fsw_ports.h"', "",
        "fsw_init();                                  /* parameters, SelfInit, constants, connections */",
        "fsw_reset(0);                                /* Reset of every module */",
        "for (;;) {                                   /* every fsw_rate_ns */",
        "    fsw_input_ports[i].write(&payload, t);   /* each input port */",
        "    fsw_step(t);",
        "    fsw_output_ports[j].read(&command);      /* each actuator command */",
        "}", "```", "",
        "`ICD.md` lists every port, its payload, units, producer and consumers; `TRACEABILITY.md` where each "
        "parameter comes from.", "",
        "## In the loop", "",
        "`fsw_host sil <address>` serves the SIL transport contract (`SIL_CONTRACT.md`): SpaceMissionStudio "
        "starts it (Flight Software tab, Run SIL...) and flies the spacecraft with its commands, comparing them "
        "with its own modules. To put flight software of your own behind the same ports, edit "
        "`adapter/fsw_adapter.c` and build `fsw_adapter_host` (`ADAPTER_GUIDE.md`).", "",
        "## Contents", "",
        "| Path | What |", "|---|---|",
        f"| `basilisk/` | Basilisk {cap.basilisk_version} sources (revision `{cap.basilisk_revision[:9]}`), unchanged, "
        "and Basilisk's licence |",
        "| `generated/cMsgCInterface/` | Basilisk's C message interface, generated from its templates (C functions only) |",
        "| `generated/fsw_config.[ch]` | Module instances, every parameter, the configuration messages, the connections |",
        "| `generated/fsw_scheduler.c` | `fsw_init`, `fsw_reset`, `fsw_step` |",
        "| `generated/fsw_ports.c` | The port tables (`fsw_ports.h`) |",
        "| `generated/fsw_log.c` | Basilisk's C logging API, without Basilisk |",
        "| `generated/fsw_layout_check.c` | Compile-time payload layout checks |",
        "| `generated/fsw_sil.c`, `fsw_transport*` | The SIL harness and its socket link |",
        "| `host/fsw_host.c` | `info`, `replay` and `sil` |",
        "| `adapter/` | The SIL adapter template for flight software of your own |",
        "| `SIL_CONTRACT.md`, `ADAPTER_GUIDE.md` | The SIL transport contract, and how to use the adapter |",
        "| `tests/` | Unit tests and the recorded replay traces |",
        "| `capture.json` | Everything recorded from the simulation (used by SpaceMissionStudio) |",
        "| `manifest.json` | Configuration digest, provenance and a SHA-256 of every file |", "",
        "## Provenance and licence", "",
        f"Configuration digest `{cap.config_digest}`. SpaceMissionStudio marks this export stale when the scenario's "
        "flight-software settings change.", "",
        "The Basilisk files are under Basilisk's ISC licence (`basilisk/LICENSE`); the generated files carry the "
        "same ISC licence.", ""])
